
module.exports = {
  // IPC events
  APP_VERSION_REQUEST: 'APP_VERSION_REQUEST',
  APP_VERSION_RESPONSE: 'APP_VERSION_RESPONSE',
  SHOW_TOOLBAR: 'SHOW_TOOLBAR',
  RESIZE_WINDOW: 'RESIZE_WINDOW',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  TOOLBAR_POSITION_CHANGE: 'TOOLBAR_POSITION_CHANGE',
  REQUEST_TOOLBAR_POSITION: 'REQUEST_TOOLBAR_POSITION',
  SHOW_CONTENT: 'SHOW_CONTENT',
  HIDE_USER_MODAL: 'HIDE_USER_MODAL',
  SHOW_USER_MODAL: 'SHOW_USER_MODAL',
  HIDDEN_USER_MODAL: 'HIDDEN_USER_MODAL',
  SET_USER_DATA: 'SET_USER_DATA',
  OPEN_EXTERNAL_LINK: 'EXTERNAL_LINK',
  REQUEST_USER_DATA: 'REQUEST_USER_DATA',
  ZOOM_FACTOR_CHANGE: 'ZOOM_FACTOR_CHANGE',
  REQUEST_ZOOM_FACTOR: 'REQUEST_ZOOM_FACTOR',
  REQUEST_HOST: 'REQUEST_HOST',
  RESPONSE_HOST: 'RESPONSE_HOST',
  SET_REGION: 'SET_REGION',

  // Menu labels
  QUIT_APP: 'Quit CareCru Hub',
};
