
import { Router } from 'express';
import { sequelizeAuthMiddleware } from '../../middleware/auth';
import createJoinObject from '../../middleware/createJoinObject';
import getResponseConfig from '../../middleware/getResponseConfig';
import accountsRouter from './accounts';
import addressRouter from './addresses';
import analyticsRouter from './analytics';
import chairsRouter from './chairs';
import connectorRouter from './connector';
import dailyScheduleRouter from './dailySchedule';
import deliveredProceduresRouter from './deliveredProcedures';
import reputationRouter from './reputation';
import enterprisesRouter from './enterprises';
import familiesRouter from './families';
import remindersRouter from './reminders';
import practitionersRouter from './practitioners';
import permissionsRouter from './permissions';
import patientsRouter from './patients';
import recurringTimeOffRouter from './recurringTimeOffs';
import usersRouter from './users';
import waitSpotsRouter from './waitSpots';
import sentRemindersRouter from './sentReminders';
import sentRecallsRouter from './sentRecalls';
import requestRouter from './request';
import updaterRouter from './updater';
import weeklySchedulesRouter from './weeklySchedules';
import invitesRouter from './invites';
import chatRouter from './chats';
import syncErrorRouter from './syncClientError';
import syncControlRouter from './syncControlRouter';
import recallsRouter from './recalls';
import appointmentsRouter from './appointment';
import callsRouter from './calls';
import servicesRouter from './services';
import segmentsRouter from './segments';
import revenueRouter from './revenue';
import patientRecallsRouter from './patientRecalls';

import tableRouter from './table';
import correspondencesRouter from './correspondences';
import renderedTemplateRouter from './renderedTemplate';

const apiRouter = Router();

apiRouter.all('*', sequelizeAuthMiddleware, createJoinObject, getResponseConfig);
apiRouter.use('/accounts', accountsRouter);
apiRouter.use('/addresses', addressRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/accounts', remindersRouter);
apiRouter.use('/accounts', invitesRouter);
apiRouter.use('/accounts', recallsRouter);
apiRouter.use('/accounts', permissionsRouter);
apiRouter.use('/accounts', renderedTemplateRouter);
apiRouter.use('/chairs', chairsRouter);
apiRouter.use('/connector', connectorRouter);
apiRouter.use('/dailySchedules', dailyScheduleRouter);
apiRouter.use('/deliveredProcedures', deliveredProceduresRouter);
apiRouter.use('/reputation', reputationRouter);
apiRouter.use('/segments', segmentsRouter);
apiRouter.use('/enterprises', enterprisesRouter);
apiRouter.use('/families', familiesRouter);
apiRouter.use('/patients', patientsRouter);
apiRouter.use('/practitioners', practitionersRouter);
apiRouter.use('/syncClientError', syncErrorRouter);
apiRouter.use('/syncClientControl', syncControlRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/waitSpots', waitSpotsRouter);
apiRouter.use('/sentReminders', sentRemindersRouter);
apiRouter.use('/sentRecalls', sentRecallsRouter);
apiRouter.use('/requests', requestRouter);
apiRouter.use('/updater', updaterRouter);
apiRouter.use('/weeklySchedules', weeklySchedulesRouter);
apiRouter.use('/chats', chatRouter);
apiRouter.use('/appointments', appointmentsRouter);
apiRouter.use('/recurringTimeOffs', recurringTimeOffRouter);
apiRouter.use('/calls', callsRouter);
apiRouter.use('/services', servicesRouter);
apiRouter.use('/table', tableRouter);
apiRouter.use('/correspondences', correspondencesRouter);
apiRouter.use('/revenue', revenueRouter);
apiRouter.use('/patientRecalls', patientRecallsRouter);

export default apiRouter;
