# create a docker-compose.yml file
version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nAet7AhJ
      POSTGRES_DB: carecru_development_docker
    ports:
      - "5432:5432"    
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
