# create a docker-compose.yml file
version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nAet7AhJ
      POSTGRES_DB: carecru_development_docker
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
  web:
    build: .
    image: carecru_web:development
    ports:
      - "5000:5000"
      - "5100:5100"
      - "3000:3000"
      - "80:80"
    volumes:
      - .:/app:rw
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    command: >
      sh -c '
      npm install &&
      npm install webpack-cli -g &&
      npm install foreman -g &&
      npm install sequelize -g &&
      npm install sequelize-cli -g &&
      npm install pg -g &&
      npm install sharp -g &&
      npm run startdev
      '

