web: node server/bin/build/server.bundle.js
cron: node server/bin/build/cron.bundle.js
reminders: node server/bin/build/reminders.bundle.js
recalls: node server/bin/build/recalls.bundle.js
reviews: node server/bin/build/reviews.bundle.js
events: node server/bin/build/events.bundle.js
firstNextLastApp: node server/bin/build/firstNextLastApp.bundle.js
correspondences: node server/bin/build/correspondences.bundle.js
lastHygiene: node server/bin/build/lastHygiene.bundle.js
release: node_modules/.bin/sequelize db:migrate
lastRecall: node server/bin/build/lastRecall.bundle.js
