export const caProvinces = [
  { value: 'Alberta' },
  { value: 'British Columbia' },
  { value: 'Manitoba' },
  { value: 'New Brunswick' },
  { value: 'Newfoundland and Labrador' },
  { value: 'Nova Scotia' },
  { value: 'Northwest Territories' },
  { value: 'Nunavut' },
  { value: 'Ontario' },
  { value: 'Prince Edward Island' },
  { value: 'Quebec' },
  { value: 'Saskatchewan' },
  { value: 'Yukon' },
];

export const countrySelector = [{ value: 'Canada'},{ value: 'United States'}];

export const usStates = [
  { value: 'Alabama' },
  { value: 'Alaska' },
  { value: 'Arizona' },
  { value: 'Arkansas' },
  { value: 'California' },
  { value: 'Colorado' },
  { value: 'Connecticut' },
  { value: 'Delaware' },
  { value: 'District of Columbia' },
  { value: 'Federated States of Micronesia' },
  { value: 'Florida' },
  { value: 'Georgia' },
  { value: 'Guam' },
  { value: 'Hawaii' },
  { value: 'Idaho' },
  { value: 'Illinois' },
  { value: 'Indiana' },
  { value: 'Iowa' },
  { value: 'Kansas' },
  { value: 'Kentucky' },
  { value: 'Louisiana' },
  { value: 'Maine' },
  { value: 'Marshall Islands' },
  { value: 'Massachusetts' },
  { value: 'Michigan' },
  { value: 'Minnesota' },
  { value: 'Mississippi' },
  { value: 'Missouri' },
  { value: 'Montana' },
  { value: 'Nebraska' },
  { value: 'Nevada' },
  { value: 'New Hampshire' },
  { value: 'New Jersey' },
  { value: 'New Mexico' },
  { value: 'New York' },
  { value: 'North Carolina' },
  { value: 'North Dakota' },
  { value: 'Northern Mariana Islands' },
  { value: 'Ohio' },
  { value: 'Oklahoma' },
  { value: 'Oregon' },
  { value: 'Palau' },
  { value: 'Pennsylvania' },
  { value: 'Puerto Rico' },
  { value: 'Rhode Island' },
  { value: 'South Carolina' },
  { value: 'South Dakota' },
  { value: 'Tennessee' },
  { value: 'Texas' },
  { value: 'Utah' },
  { value: 'Vermont' },
  { value: 'Virgin Islands' },
  { value: 'Virginia' },
  { value: 'Washington' },
  { value: 'West Virginia' },
  { value: 'Wisconsin' },
  { value: 'Wyoming' },
];

