
export const SET_IS_COLLAPSED = 'SET_IS_COLLAPSED';

export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';
export const CREATE_ENTITY = 'CREATE_ENTITY';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const DELETE_ENTITY = 'DELETE_ENTITY';
